<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Bookmaker;

class BookmakerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Bookmaker::query()->updateOrCreate(
            ['key' => '1xbet'],
            ['key' => '1xbet',
                'name' => '1XBET',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => '1xbet.svg',
                'logo_color' => '#1A5685',
                'promo_code' => 'GENER55',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Use the promo code GENER55 and get $1950 + 150 free spins for casino play',
                'bonus_label_1_es' => 'Utiliza el código promocional GENER55 y obtén 1950 $ + 150 giros gratis para jugar en el casino',
                'bonus_label_1_fr' => 'Utilisez le code promo GENER55 et obtenez 1950 $ + 150 tours gratuits pour jouer au casino',
                'bonus_label_1_pt' => 'Utilize o código promocional GENER55 e receba $ 1950 + 150 rodadas grátis para jogar no cassino',
                'bonus_label_2_en' => 'Or use the promo code GENER55 and get 120% up to $400 for sports betting',
                'bonus_label_2_es' => 'O utiliza el código promocional GENER55 y obtén el 120 % hasta 400 $ para apuestas deportivas',
                'bonus_label_2_fr' => 'Ou utilisez le code promo GENER55 et obtenez 120 % jusqu’à 400 $ pour les paris sportifs',
                'bonus_label_2_pt' => 'Ou utilize o código promocional GENER55 e receba 120 % até $ 400 para apostas esportivas',
                'warning_en' => 'In this detailed review of the bookmaker 1XBET, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support',
                'warning_es' => 'En esta revisión detallada de la casa de apuestas 1XBET, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte',
                'warning_fr' => "Dans cet examen détaillé du bookmaker 1XBET, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support.",
                'warning_pt' => 'Nesta análise detalhada da casa de apostas 1XBET, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte',
                'licensed' => 'Curacao, eGaming, Kahnawake Gaming Commission',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'info-en@1xbet.com',
                'phone' => '+49 800 5889574',
                'active' => 1,
                'order' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'melbet'],
            ['key' => 'melbet',
                'name' => 'MelBet',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => 'melbet.svg',
                'logo_color' => '#000809',
                'promo_code' => 'CLUB500',
                'bonus_available' => 0,
                'bonus_label_1_en' => "Get a 150% WELCOME BONUS UP TO $450 with the promo code CLUB500 for sports betting",
                'bonus_label_1_es' => "Obtén un 150% de BONO DE BIENVENIDA HASTA 450 $ con el código promocional CLUB500 para apuestas deportivas",
                'bonus_label_1_fr' => "Obtenez 150 % de BONUS DE BIENVENUE JUSQU’À 450 $ avec le code promo CLUB500 pour les paris sportifs",
                'bonus_label_1_pt' => "Receba 150% de BÔNUS DE BOAS-VINDAS ATÉ US$ 450 com o código promocional CLUB500 para apostas esportivas",
                'bonus_label_2_en' => "Also, enjoy a FANTASTIC CASINO WELCOME PACKAGE with a 450% bonus — GET UP TO $2000 + 250 FS",
                'bonus_label_2_es' => "Y también un FANTÁSTICO PAQUETE DE BIENVENIDA DE CASINO con un bono del 450% — OBTÉN HASTA 2000 $ + 250 giros gratis",
                'bonus_label_2_fr' => "Et profitez également d’un FANTASTIQUE PACK DE BIENVENUE CASINO avec un bonus de 450 % — RECEVEZ JUSQU’À 2000 $ + 250 tours gratuits",
                'bonus_label_2_pt' => "E ainda um FANTÁSTICO PACOTE DE BOAS-VINDAS DE CASSINO com bônus de 450% — GANHE ATÉ US$ 2000 + 250 rodadas grátis",
                'warning_en' => "In this detailed review of the bookmaker MelBet, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support",
                'warning_es' => "En esta revisión detallada de la casa de apuestas MelBet, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte",
                'warning_fr' => "Dans cet examen détaillé du bookmaker MelBet, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support",
                'warning_pt' => "Nesta análise detalhada da casa de apostas MelBet, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte",
                'licensed' => 'Curacao',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'info-en@melbet.org',
                'phone' => '+442038077601',
                'active' => 1,
                'order' => 2,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'betwinner'],
            ['key' => 'betwinner',
             'name' => 'BetWinner',
             'url' => 'https://1wfzws.life/?p=ayxs',
             'logo' => 'betwinner.svg',
             'logo_color' => '#1a674b',
             'promo_code' => 'NEWBONUS',
             'bonus_available' => 0,
             'bonus_label_1_en' => 'Welcome package up to $1500 + 150 FS with the promo code NEWBONUS',
             'bonus_label_1_es' => 'Paquete de bienvenida de hasta 1500 $ + 150 giros gratis con el código promocional NEWBONUS',
             'bonus_label_1_fr' => 'Pack de bienvenue jusqu’à 1500 $ + 150 tours gratuits avec le code promo NEWBONUS',
             'bonus_label_1_pt' => 'Pacote de boas-vindas de até US$ 1500 + 150 rodadas grátis com o código promocional NEWBONUS',
             'bonus_label_2_en' => 'Top up your deposits and get a bonus of up to $1500 + 150 FS!',
             'bonus_label_2_es' => 'Recarga tus depósitos y obtén un bono de hasta 1500 $ + 150 giros gratis',
             'bonus_label_2_fr' => 'Alimentez vos dépôts et obtenez un bonus allant jusqu’à 1500 $ + 150 tours gratuits !',
             'bonus_label_2_pt' => 'Recarregue seus depósitos e receba um bônus de até US$ 1500 + 150 rodadas grátis!',
                'warning_en' => "In this detailed review of the bookmaker BetWinner, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support",
                'warning_es' => "En esta revisión detallada de la casa de apuestas BetWinner, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte",
                'warning_fr' => "Dans cet examen détaillé du bookmaker BetWinner, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support",
                'warning_pt' => "Nesta análise detalhada da casa de apostas BetWinner, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte",
             'licensed' => 'Curacao',
             'streaming' => 1,
             'tested' => 1,
             'email' => 'support@betwinner.com',
             'phone' => '+44 203 936 2996',
             'active' => 1,
             'order' => 3,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '1win'],
            ['key' => '1win',
                'name' => '1win',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => '1win.svg',
                'logo_color' => '#1b243a',
                'promo_code' => '1W500GAX',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Use promo code 1W500GAX',
                'bonus_label_1_es' => 'Usa el código promocional 1W500GAX',
                'bonus_label_1_fr' => 'Utilisez le code promo 1W500GAX',
                'bonus_label_1_pt' => 'Use o código promocional 1W500GAX',
                'bonus_label_2_en' => 'Enter the 1win promo code 1W500GAX during registration, and you can receive a 500% deposit bonus up to $1025.',
                'bonus_label_2_es' => 'Ingresa el código promocional de 1win 1W500GAX durante el registro y podrás recibir un bono de depósito del 500% hasta 1025 $',
                'bonus_label_2_fr' => 'Saisissez le code promo 1win 1W500GAX lors de l’inscription et vous pourrez recevoir un bonus de dépôt de 500 % jusqu’à 1025 $',
                'bonus_label_2_pt' => 'Insira o código promocional 1win 1W500GAX durante o registro e você poderá receber um bônus de depósito de 500% até US$ 1025',
                'warning_en' => "In this detailed review of the bookmaker 1win, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support",
                'warning_es' => "En esta revisión detallada de la casa de apuestas 1win, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte",
                'warning_fr' => "Dans cet examen détaillé du bookmaker 1win, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support",
                'warning_pt' => "Nesta análise detalhada da casa de apostas 1win, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte",
                'licensed' => '',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'support@1win.xyz',
                'phone' => '',
                'active' => 1,
                'order' => 4,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'mostbet'],
            ['key' => 'mostbet',
                'name' => 'MOSTBET',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => 'mostbet.svg',
                'logo_color' => '#003b77',
                'promo_code' => 'HUGE',
                'bonus_available' => 0,
                'bonus_label_1_en' => '125% bonus on your first sports betting deposit with our promo code HUGE for deposits from $10',
                'bonus_label_1_es' => 'Bono del 125% en tu primer depósito para apuestas deportivas con nuestro código promocional HUGE en depósitos desde 10 $',
                'bonus_label_1_fr' => 'Bonus de 125 % sur votre premier dépôt pour les paris sportifs avec notre code promo HUGE pour les dépôts à partir de 10 $',
                'bonus_label_1_pt' => 'Bônus de 125% no seu primeiro depósito para apostas esportivas com o nosso código promocional HUGE para depósitos a partir de US$ 10',
                'bonus_label_2_en' => 'Also, 125% + 250 FS bonus on your first casino deposit with our promo code HUGE for deposits from $10',
                'bonus_label_2_es' => 'Además, bono del 125% + 250 giros gratis en tu primer depósito en el casino con nuestro código promocional HUGE en depósitos desde 10 $',
                'bonus_label_2_fr' => 'De plus, bonus de 125 % + 250 tours gratuits sur votre premier dépôt au casino avec notre code promo HUGE pour les dépôts à partir de 10 $',
                'bonus_label_2_pt' => 'Além disso, bônus de 125% + 250 rodadas grátis no seu primeiro depósito no cassino com o nosso código promocional HUGE para depósitos a partir de US$ 10',
                'warning_en' => "In this detailed review of the bookmaker MOSTBET, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support",
                'warning_es' => "En esta revisión detallada de la casa de apuestas MOSTBET, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte",
                'warning_fr' => "Dans cet examen détaillé du bookmaker MOSTBET, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support",
                'warning_pt' => "Nesta análise detalhada da casa de apostas MOSTBET, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte",
                'licensed' => 'Curacao',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'SUPPORT-EN@MOSTBET.COM',
                'phone' => '',
                'active' => 1,
                'order' => 5,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'paripesa'],
            ['key' => 'paripesa',
                'name' => 'PARIPESA',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => 'paripesa.svg',
                'logo_color' => '#0f2595',
                'promo_code' => 'TOPBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Register on the PARIPESA website with the promo code TOPBONUS and get a 100% bonus of up to $300 on your first deposit!',
                'bonus_label_1_es' => 'Regístrate en el sitio web de PARIPESA con el código promocional TOPBONUS y recibe un bono del 100% de hasta 300 $ en tu primer depósito',
                'bonus_label_1_fr' => 'Inscrivez-vous sur le site de PARIPESA avec le code promo TOPBONUS et recevez un bonus de 100 % jusqu’à 300 $ sur votre premier dépôt !',
                'bonus_label_1_pt' => 'Registre-se no site da PARIPESA com o código promocional TOPBONUS e receba um bônus de 100% de até US$ 300 no seu primeiro depósito!',
                'bonus_label_2_en' => 'Welcome package up to $1500 + 150 FS for casino games with the promo code TOPBONUS',
                'bonus_label_2_es' => 'Paquete de bienvenida de hasta 1500 $ + 150 giros gratis para juegos de casino con el código promocional TOPBONUS',
                'bonus_label_2_fr' => 'Pack de bienvenue jusqu’à 1500 $ + 150 tours gratuits pour les jeux de casino avec le code promo TOPBONUS',
                'bonus_label_2_pt' => 'Pacote de boas-vindas de até US$ 1500 + 150 rodadas grátis para jogos de cassino com o código promocional TOPBONUS',
                'warning_en' => "In this detailed review of the bookmaker PARIPESA, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support",
                'warning_es' => "En esta revisión detallada de la casa de apuestas PARIPESA, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte",
                'warning_fr' => "Dans cet examen détaillé du bookmaker PARIPESA, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support",
                'warning_pt' => "Nesta análise detalhada da casa de apostas PARIPESA, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte",
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'support-en@PariPesa.com',
                'phone' => '+254 700 123456',
                'active' => 1,
                'order' => 6,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '4rabet'],
            ['key' => '4rabet',
                'name' => '4RABET',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => '4rabet.svg',
                'logo_color' => '#0f0710',
                'promo_code' => '4rasport22',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Choose a package with a total bonus fund of 700% for true sports betting enthusiasts with the promo code 4rasport22',
                'bonus_label_1_es' => 'Elige un paquete con un fondo de bonificación total del 700% para verdaderos entusiastas de las apuestas deportivas con el código promocional 4rasport22',
                'bonus_label_1_fr' => 'Choisissez un package avec un fonds de bonus total de 700 % pour les véritables passionnés de paris sportifs avec le code promo 4rasport22',
                'bonus_label_1_pt' => 'Escolha um pacote com um fundo de bônus total de 700% para verdadeiros entusiastas de apostas esportivas com o código promocional 4rasport22',
                'bonus_label_2_en' => 'Or get a 150% bonus on your first deposit and enjoy the best Live Casino games!',
                'bonus_label_2_es' => 'O recibe un bono del 150% en tu primer depósito y disfruta de los mejores juegos de Live Casino',
                'bonus_label_2_fr' => 'Ou obtenez un bonus de 150 % sur votre premier dépôt et profitez des meilleurs jeux de Live Casino !',
                'bonus_label_2_pt' => 'Ou receba um bônus de 150% no seu primeiro depósito e aproveite os melhores jogos de Live Casino!',
                'warning_en' => "In this detailed review of the bookmaker 4RABET, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support",
                'warning_es' => "En esta revisión detallada de la casa de apuestas 4RABET, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte",
                'warning_fr' => "Dans cet examen détaillé du bookmaker 4RABET, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support",
                'warning_pt' => "Nesta análise detalhada da casa de apostas 4RABET, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte",
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 0,
                'email' => 'support@4rabet.com',
                'phone' => '',
                'active' => 1,
                'order' => 7,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '888starz'],
            ['key' => '888starz',
             'name' => '888Starz',
             'url' => 'https://1wfzws.life/?p=ayxs',
             'logo' => '888starz.svg',
             'logo_color' => '#0f0710',
             'promo_code' => 'WORLDCUP',
             'bonus_available' => 0,
             'bonus_label_1_en' => 'Sports welcome package up to $400 with promo code WORLDCUP',
             'bonus_label_1_es' => 'Paquete de bienvenida deportiva de hasta $400 con el código promocional WORLDCUP',
             'bonus_label_1_fr' => 'Pack de bienvenue sportif jusqu’à 400 $ avec le code promo WORLDCUP',
             'bonus_label_1_pt' => 'Pacote de boas-vindas esportivo de até $400 com o código promocional WORLDCUP',
             'bonus_label_2_en' => 'Welcome package up to 1500 EUR + 150 FS with promo code WORLDCUP',
             'bonus_label_2_es' => 'Paquete de bienvenida de hasta 1500 EUR + 150 giros gratis con el código promocional WORLDCUP',
             'bonus_label_2_fr' => 'Pack de bienvenue jusqu’à 1500 EUR + 150 tours gratuits avec le code promo WORLDCUP',
             'bonus_label_2_pt' => 'Pacote de boas-vindas de até 1500 EUR + 150 rodadas grátis com o código promocional WORLDCUP',
                'warning_en' => "In this detailed review of the bookmaker 888Starz, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support",
                'warning_es' => "En esta revisión detallada de la casa de apuestas 888Starz, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte",
                'warning_fr' => "Dans cet examen détaillé du bookmaker 888Starz, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support",
                'warning_pt' => "Nesta análise detalhada da casa de apostas 888Starz, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte",
             'licensed' => 'Curacao',
             'streaming' => 1,
             'tested' => 1,
             'email' => 'support-en@888starz.bet',
             'phone' => '+357 97630833',
             'active' => 1,
             'order' => 8,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'megapari'],
            ['key' => 'megapari',
                'name' => 'MegaPari',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => 'megapari.svg',
                'logo_color' => '#000000',
                'promo_code' => 'NEWBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Welcome package up to $350 for sports betting! Get a 100% bonus on your first deposit with the promo code NEWBONUS',
                'bonus_label_1_es' => '¡Paquete de bienvenida de hasta $350 para apuestas deportivas! Obtén un bono del 100% en tu primer depósito con el código promocional NEWBONUS',
                'bonus_label_1_fr' => 'Pack de bienvenue jusqu’à 350 $ pour les paris sportifs ! Recevez un bonus de 100 % sur votre premier dépôt avec le code promotionnel NEWBONUS',
                'bonus_label_1_pt' => 'Pacote de boas-vindas de até $350 para apostas esportivas! Receba um bônus de 100% no seu primeiro depósito com o código promocional NEWBONUS',
                'bonus_label_2_en' => 'Welcome package up to $1500 + 150 FS for casino games',
                'bonus_label_2_es' => 'Paquete de bienvenida de hasta $1500 + 150 giros gratis para juegos de casino',
                'bonus_label_2_fr' => 'Pack de bienvenue jusqu’à 1500 $ + 150 tours gratuits pour les jeux de casino',
                'bonus_label_2_pt' => 'Pacote de boas-vindas de até $1500 + 150 rodadas grátis para jogos de cassino',
                'warning_en' => "In this detailed review of the bookmaker MegaPari, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support",
                'warning_es' => "En esta revisión detallada de la casa de apuestas MegaPari, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte",
                'warning_fr' => "Dans cet examen détaillé du bookmaker MegaPari, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support",
                'warning_pt' => "Nesta análise detalhada da casa de apostas MegaPari, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte",
                'licensed' => 'Curacao',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'support@megapari.com',
                'phone' => '+441863440619',
                'active' => 1,
                'order' => 9,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '22bet'],
            ['key' => '22bet',
                'name' => '22BET',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => '22bet.svg',
                'logo_color' => '#064146',
                'promo_code' => 'HUGE',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Enter the promo code HUGE and get an additional 100% on your first deposit up to $100 for sports betting,',
                'bonus_label_1_es' => 'Introduce el código promocional HUGE y recibe un 100% adicional en tu primer depósito hasta $100 para apuestas deportivas,',
                'bonus_label_1_fr' => 'Saisissez le code promo HUGE et obtenez 100 % supplémentaires sur votre premier dépôt jusqu’à 100 $ pour les paris sportifs,',
                'bonus_label_1_pt' => 'Insira o código promocional HUGE e receba 100% adicionais no seu primeiro depósito até $100 para apostas esportivas,',
                'bonus_label_2_en' => 'or use the promo code HUGE to receive $300 + 30 free spins for casino games after your first deposit',
                'bonus_label_2_es' => 'o utiliza el código promocional HUGE para obtener $300 + 30 giros gratis para juegos de casino después de tu primer depósito',
                'bonus_label_2_fr' => 'ou utilisez le code promo HUGE pour recevoir 300 $ + 30 tours gratuits pour les jeux de casino après votre premier dépôt',
                'bonus_label_2_pt' => 'ou utilize o código promocional HUGE para receber $300 + 30 rodadas grátis para jogos de cassino após o seu primeiro depósito',
                'warning_en' => "In this detailed review of the bookmaker 22BET, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support",
                'warning_es' => "En esta revisión detallada de la casa de apuestas 22BET, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte",
                'warning_fr' => "Dans cet examen détaillé du bookmaker 22BET, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support",
                'warning_pt' => "Nesta análise detalhada da casa de apostas 22BET, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte",
                'licensed' => 'UK Gambling Commission, Curacao',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'support-en@22bet.com',
                'phone' => '+357 99 816806',
                'active' => 1,
                'order' => 10,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'linebet'],
            ['key' => 'linebet',
                'name' => 'Linebet',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => 'linebet.svg',
                'logo_color' => '#204f14',
                'promo_code' => 'BNB777',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Welcome bonus on sports up to $120 with the promo code BNB777',
                'bonus_label_1_es' => 'Bono de bienvenida en deportes hasta $120 con el código promocional BNB777',
                'bonus_label_1_fr' => 'Bonus de bienvenue sur les sports jusqu’à 120 $ avec le code promo BNB777',
                'bonus_label_1_pt' => 'Bônus de boas-vindas em esportes até $120 com o código promocional BNB777',
                'bonus_label_2_en' => 'Welcome package up to $1750 + 150 free spins with the promo code BNB777',
                'bonus_label_2_es' => 'Paquete de bienvenida hasta $1750 + 150 giros gratis con el código promocional BNB777',
                'bonus_label_2_fr' => 'Pack de bienvenue jusqu’à 1750 $ + 150 tours gratuits avec le code promo BNB777',
                'bonus_label_2_pt' => 'Pacote de boas-vindas até $1750 + 150 rodadas grátis com o código promocional BNB777',
                'warning_en' => "In this detailed review of the bookmaker Linebet, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support",
                'warning_es' => "En esta revisión detallada de la casa de apuestas Linebet, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte",
                'warning_fr' => "Dans cet examen détaillé du bookmaker Linebet, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support",
                'warning_pt' => "Nesta análise detalhada da casa de apostas Linebet, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte",
                'licensed' => 'Curacao',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'support-in@linebet.com',
                'phone' => '+44 20 4577 0803',
                'active' => 1,
                'order' => 11,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '20bet'],
            ['key' => '20bet',
                'name' => '20BET',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => '20bet.svg',
                'logo_color' => '#081d36',
                'promo_code' => 'MISSING',
                'bonus_available' => 0,
                'bonus_label_1_en' => '100% bonus on the first deposit up to €100 for sports betting with promo code MISSING',
                'bonus_label_1_es' => 'Bono del 100% en el primer depósito hasta 100 € para apuestas deportivas con el código promocional MISSING',
                'bonus_label_1_fr' => 'Bonus de 100 % sur le premier dépôt jusqu’à 100 € pour les paris sportifs avec le code promo MISSING',
                'bonus_label_1_pt' => 'Bônus de 100% no primeiro depósito até 100 € para apostas desportivas com o código promocional MISSING',
                'bonus_label_2_en' => '100% bonus on the first deposit up to €120 for casino games with promo code MISSING',
                'bonus_label_2_es' => 'Bono del 100% en el primer depósito hasta 120 € para juegos de casino con el código promocional MISSING',
                'bonus_label_2_fr' => 'Bonus de 100 % sur le premier dépôt jusqu’à 120 € pour les jeux de casino avec le code promo MISSING',
                'bonus_label_2_pt' => 'Bônus de 100% no primeiro depósito até 120 € para jogos de casino com o código promocional MISSING',
                'warning_en' => "In this detailed review of the bookmaker 20BET, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support",
                'warning_es' => "En esta revisión detallada de la casa de apuestas 20BET, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte",
                'warning_fr' => "Dans cet examen détaillé du bookmaker 20BET, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support",
                'warning_pt' => "Nesta análise detalhada da casa de apostas 20BET, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte",
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'support@20bet.com',
                'phone' => '',
                'active' => 1,
                'order' => 12,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'betandyou'],
            ['key' => 'betandyou',
                'name' => 'BETANDYOU',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => 'betandyou.svg',
                'logo_color' => '#000000',
                'promo_code' => 'MAXBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Register and get a bonus of up to $120 on your first deposit!',
                'bonus_label_1_es' => '¡Regístrate y recibe un bono de hasta $120 en tu primer depósito!',
                'bonus_label_1_fr' => 'Inscrivez-vous et obtenez un bonus allant jusqu’à 120 $ sur votre premier dépôt !',
                'bonus_label_1_pt' => 'Registre-se e receba um bônus de até $120 no seu primeiro depósito!',
                'bonus_label_2_en' => 'Welcome package up to $1500 + 150 free spins for casino games. Make deposits and receive bonuses!',
                'bonus_label_2_es' => 'Paquete de bienvenida de hasta $1500 + 150 giros gratis para juegos de casino. ¡Haz depósitos y recibe bonos!',
                'bonus_label_2_fr' => 'Pack de bienvenue jusqu’à 1500 $ + 150 tours gratuits pour les jeux de casino. Effectuez des dépôts et recevez des bonus !',
                'bonus_label_2_pt' => 'Pacote de boas-vindas de até $1500 + 150 rodadas grátis para jogos de cassino. Faça depósitos e receba bônus!',
                'warning_en' => "In this detailed review of the bookmaker BETANDYOU, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support",
                'warning_es' => "En esta revisión detallada de la casa de apuestas BETANDYOU, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte",
                'warning_fr' => "Dans cet examen détaillé du bookmaker BETANDYOU, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support",
                'warning_pt' => "Nesta análise detalhada da casa de apostas BETANDYOU, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte",
                'licensed' => 'Curacao',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'support-en@betandyou.com',
                'phone' => '',
                'active' => 1,
                'order' => 13,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'ivibet'],
            ['key' => 'ivibet',
                'name' => 'Ivibet',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => 'ivibet.svg',
                'logo_color' => '#07C99A',
                'promo_code' => 'MAXBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => '100% up to $150 first deposit bonus for sports betting with promo code MAXBONUS',
                'bonus_label_1_es' => 'Bono del 100% hasta $150 en el primer depósito para apuestas deportivas con el código promocional MAXBONUS',
                'bonus_label_1_fr' => 'Bonus de 100% jusqu’à 150 $ sur le premier dépôt pour les paris sportifs avec le code promo MAXBONUS',
                'bonus_label_1_pt' => 'Bônus de 100% até $150 no primeiro depósito para apostas esportivas com o código promocional MAXBONUS',
                'bonus_label_2_en' => '100% up to $100 + 120 FS first deposit bonus for casino games with promo code MAXBONUS',
                'bonus_label_2_es' => 'Bono del 100% hasta $100 + 120 giros gratis en el primer depósito para juegos de casino con el código promocional MAXBONUS',
                'bonus_label_2_fr' => 'Bonus de 100% jusqu’à 100 $ + 120 tours gratuits sur le premier dépôt pour les jeux de casino avec le code promo MAXBONUS',
                'bonus_label_2_pt' => 'Bônus de 100% até $100 + 120 giros grátis no primeiro depósito para jogos de cassino com o código promocional MAXBONUS',
                'warning_en' => "In this detailed review of the bookmaker ivibet, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support",
                'warning_es' => "En esta revisión detallada de la casa de apuestas ivibet, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte",
                'warning_fr' => "Dans cet examen détaillé du bookmaker ivibet, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support",
                'warning_pt' => "Nesta análise detalhada da casa de apostas ivibet, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte",
                'licensed' => 'Curacao, Kahnawake',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'support@ivibet.com',
                'phone' => '',
                'active' => 1,
                'order' => 14,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '1xbit'],
            ['key' => '1xbit',
                'name' => '1xBit',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => '1xbit.svg',
                'logo_color' => '#212121',
                'promo_code' => 'NEWBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Registration bonus up to 7 BTC + 250 FS with the promo code NEWBONUS for casino play!',
                'bonus_label_1_es' => '¡Bono de registro de hasta 7 BTC + 250 giros gratis con el código promocional NEWBONUS para jugar en el casino!',
                'bonus_label_1_fr' => 'Bonus de bienvenue jusqu’à 7 BTC + 250 tours gratuits avec le code promo NEWBONUS pour jouer au casino !',
                'bonus_label_1_pt' => 'Bônus de registro de até 7 BTC + 250 giros grátis com o código promocional NEWBONUS para jogar no cassino!',
                'bonus_label_2_en' => 'Take advantage of this unique offer for new players and get a bonus of up to 7 BTC + 250 FS!',
                'bonus_label_2_es' => '¡Aprovecha esta oferta única para nuevos jugadores y recibe un bono de hasta 7 BTC + 250 giros gratis!',
                'bonus_label_2_fr' => 'Profitez de cette offre unique pour les nouveaux joueurs et recevez un bonus jusqu’à 7 BTC + 250 tours gratuits !',
                'bonus_label_2_pt' => 'Aproveite esta oferta exclusiva para novos jogadores e receba um bônus de até 7 BTC + 250 giros grátis!',
                'warning_en' => "In this detailed review of the bookmaker 1xBit, we will cover Sports, Casino, Odds and Limits, Deposits and Withdrawals, Support",
                'warning_es' => "En esta revisión detallada de la casa de apuestas 1xBit, analizaremos Deportes, Casino, Cuotas y Límites, Depósitos y Retiros, Soporte",
                'warning_fr' => "Dans cet examen détaillé du bookmaker 1xBit, nous aborderons Sports, Casino, Cotes et Limites, Dépôts et Retraits, Support",
                'warning_pt' => "Nesta análise detalhada da casa de apostas 1xBit, abordaremos Esportes, Cassino, Odds e Limites, Depósitos e Saques, Suporte",
                'licensed' => 'Curacao',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'support-en@1x-bit.com',
                'phone' => '',
                'active' => 1,
                'order' => 15,
            ]
        );
    }
}
